fix(ios): removed fb messenger example code.
tidev/ti.facebook pull request #110
Opened 2019-09-13 18:09 UTC by vijaysingh-axway

2019-09-13 18:13 UTC, vijaysingh-axway commented
@lokeshchdhry Please merge this after merging https://github.com/appcelerator-modules/ti.facebook/pull/103.

2019-09-13 18:19 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: Here are the artifacts produced:
- <a href="https://jenkins.appcelerator.org/job/modules/job/ti.facebook/job/PR-110/1/artifact/facebook-android-8.0.0.zip">facebook-android-8.0.0.zip</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 51 tests are passing.
  </td>
    </tr>
  </tbody>
</table>

Dependencies with modified semantic versioning:
* <a href='https://www.npmjs.com/package/karma-titanium-launcher'><code>karma-titanium-launcher</code></a> - from <code>^0.6.0</code> to <code>^0.7.4</code>
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 88d22fb13637807d6452f51fd62bf28aaf98f1f1
</p>

2019-09-13 22:14 UTC, keerthi1032 commented
@sgtcoolguy  jenkin is failing. iOS module did not get generated to test. can you please take a look.

2019-09-17 14:30 UTC, sgtcoolguy requested changes
The removal of the messenger example is fine. The issue is that the guard for places not to be shown on Android was removed.

2019-09-17 14:30 UTC, sgtcoolguy commented on example/app.js
> -if(Ti.Platform.osname !== 'android') {
Don't we still need this guard? I don't think we support the Places API on Android.

2019-09-17 14:37 UTC, sgtcoolguy commented
manually merged after adding android guard back into example

2019-09-17 14:37 UTC, closed without merging