[MOD-2287] iOS/Android: Add missing login button properties
tidev/ti.facebook pull request #62
Opened 2016-08-27 13:12 UTC by hansemannn

JIRA: https://jira.appcelerator.org/browse/MOD-2287

🔥 Work in progress 🔥

2016-08-30 20:42 UTC, AngelkPetkov commented
CR on iOS looks good, @ashcoding can you please review android side, LGTM but best to check. If good. iOS **Approved** also resolve merge conflicts please.

2016-09-17 03:01 UTC, ashcoding commented on android/src/facebook/LoginButtonView.java
> +			if (tooltipColorStyle == TiFacebookModule.LOGIN_BUTTON_TOOLTIP_STYLE_NEUTRAL_GRAY) {
Wrong usage. Please use ```.equals()``` instead of ```==``` for Strings.

2016-09-17 03:01 UTC, ashcoding commented on android/src/facebook/LoginButtonView.java
> +			} else if (tooltipColorStyle == TiFacebookModule.LOGIN_BUTTON_TOOLTIP_STYLE_FRIENDLY_BLUE) {
Same. Wrong usage. Please use ```.equals()``` instead of ```==``` for Strings.

2016-09-17 03:02 UTC, ashcoding requested changes
I've left comments on the wrong usage of `==` in comparing Strings in java. Please review and change it.

2016-09-23 23:34 UTC, hansemannn commented on android/src/facebook/LoginButtonView.java
> +			if (tooltipColorStyle == TiFacebookModule.LOGIN_BUTTON_TOOLTIP_STYLE_NEUTRAL_GRAY) {
Addressed

2016-09-23 23:34 UTC, hansemannn commented on android/src/facebook/LoginButtonView.java
> +			} else if (tooltipColorStyle == TiFacebookModule.LOGIN_BUTTON_TOOLTIP_STYLE_FRIENDLY_BLUE) {
Addressed

2016-09-23 23:36 UTC, hansemannn commented
@garymathews Addressed the two comments, can you take over from @ashcoding?

2016-09-29 17:53 UTC, garymathews commented
@hansemannn 

CR: **PASS**

👍

2016-09-29 18:15 UTC, hansemannn commented
Sure thing, please squash them

2016-10-24 07:30 UTC, merged

2016-10-24 07:30 UTC, cheekiatng commented
APPROVED