Move to Jenkinsfile for builds
tidev/ti.facebook pull request #84
Opened 2017-03-10 18:42 UTC by sgtcoolguy

2017-03-10 19:54 UTC, hansemannn requested changes

2017-03-10 19:54 UTC, hansemannn commented on Jenkinsfile
> +def tiSDKVersion = '5.3.0.GA'
We should use 6.0.2.GA

2017-03-10 19:54 UTC, hansemannn commented on Jenkinsfile
> +              sh 'ant'
We should use `ti build -p android --build-only` or the Appc-CLI `appc run -p android --build-only`.

2017-03-10 19:54 UTC, hansemannn commented on Jenkinsfile
> +          sh './build.py'
We should use `ti build -p ios --build-only` or the Appc-CLI `appc run -p ios --build-only`.

2017-03-11 08:37 UTC, hansemannn approved these changes

2017-03-13 17:23 UTC, sgtcoolguy commented
https://jira.appcelerator.org/browse/TIMOB-24480 is breaking the `appc ti build` for android here. Not sure if we want to just get that merged and update the Jenkinsfile here to use 6.0.3.GA whenever that comes out, or use ant to build the android half for now and update when 6.0.3.GA goes out.

2017-03-23 14:32 UTC, merged