Enhancing logPurchase and exposing EVENT_NAME_* and EVENT_PARAM_* constants
tidev/ti.facebook pull request #98
Opened 2019-01-22 11:49 UTC by AndreaVitale

In a project I need to log all users activities via Facebook AppEvents. For this reason we need all necessary `EVENT_NAME_*` and `EVENT_PARAM_*` constants and use them with `logCustomEvent`method.

Another need was to track, when logging a purchase, all informations about the product like `EVENT_PARAM_CONTENT_TYPE` `EVENT_PARAM_CONTENT_ID` and others.

2019-03-22 12:29 UTC, SquirrelMobile commented
I need this feature too ! When this will be implemented ?

2019-03-22 12:31 UTC, hansemannn commented on android/src/facebook/TiFacebookModule.java
> +        Bundle paramBundle = parameters != null ? Utils.mapToBundle(parameters) : null;
I don't think the null-check is required. `mapToBundle` already performs a null check.

2019-03-22 12:31 UTC, hansemannn commented on ios/Classes/Module/FacebookModule.m
> +  ENSURE_TYPE([purchase objectAtIndex:2], NSDictionary);
This should be optional (`ENSURE_TYPE_OR_NIL`).

2019-03-22 12:32 UTC, hansemannn commented on ios/Classes/Module/FacebookModule.m
> +  [FBSDKAppEvents logPurchase:[amount doubleValue] currency:currency parameters:parameters];
If `parameters` is `nil`, either the other method should be used or you need to check if `nil` is okay to pass here.

2019-03-22 12:33 UTC, hansemannn commented on ios/Classes/Module/FacebookModule.m
> +    [FBSDKAppEvents logEvent:FBSDKAppEventNameCompletedRegistration parameters:params];
This can be done by reusing the existing log method + the key `fb_registration_method` to keep it generic. Same for Android.

2019-03-22 12:34 UTC, hansemannn approved these changes
I left some changes that should be applied prior to merging. But in the end, one of the Appc team members need to merge this. cc @janvennemann @garymathews @vijaysingh-axway

2019-04-01 19:52 UTC, SquirrelMobile commented
up to this feature @janvennemann @garymathews @vijaysingh-axway can you merge with the actual code please ?

2019-04-16 09:00 UTC, SquirrelMobile commented
Any chance to get this feature soon please ?

2019-04-23 19:11 UTC, hansemannn commented
@vijaysingh-axway Can you please merge this? The changes look fine and have been tested in production.

2019-04-29 19:04 UTC, vijaysingh-axway commented
@hansemannn  @AndreaVitale  Thanks for PR. Can you please create a ticket with a test case for this? So that QE can verify it. And we will be good to go with this. Thanks!

2019-05-03 09:38 UTC, Topener commented
Ticket has been created in the meantime: https://jira.appcelerator.org/browse/MOD-2510

2019-05-10 18:32 UTC, SquirrelMobile commented
@vijaysingh-axway all the checks is passed ? This functionnality is merge with master ? Do we have a new version available please ? Thank you.

2019-05-21 23:17 UTC, vijaysingh-axway approved these changes
@garymathews  @jquick-axway Can you please check for android? Thanks!

2019-05-21 23:21 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 70 tests are passing.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bfbce0f9ef8bbbcd767e3d2d403eddc0eee080cc
</p>

2019-05-22 00:02 UTC, vijaysingh-axway requested changes
Need to address the comments and doc update as well. Thanks!

2019-05-22 00:02 UTC, vijaysingh-axway commented on ios/Classes/Module/FacebookModule.m
> +  NSDictionary *parameters = [purchase objectAtIndex:2];
If there is only 2 parameters, it will crash here. Please add proper check on parameter count.

2019-05-27 10:21 UTC, SquirrelMobile commented
@vijaysingh-axway how to download the artefact with the changes please : https://github.com/appcelerator-modules/ti.facebook/pull/98#issuecomment-494594480 ?

2019-05-29 00:25 UTC, vijaysingh-axway commented
> @vijaysingh-axway how to download the artefact with the changes please : [#98 (comment)](https://github.com/appcelerator-modules/ti.facebook/pull/98#issuecomment-494594480) ?

@AndreaVitale  Are you not able to download on click of links in the comment ?

2019-05-30 21:31 UTC, vijaysingh-axway approved these changes

2019-05-30 21:32 UTC, merged

2019-05-30 22:22 UTC, vijaysingh-axway commented
@AndreaVitale  Get pre release modules from https://github.com/appcelerator-modules/ti.facebook/releases. Thanks!